##########################################################################
# Object files which are part of iGame
##########################################################################

OBJS		= src/funcs.o src/iGameGUI.o src/iGameMain.o src/strfuncs.o src/fsfuncs.o src/blacklist.o src/WinBlacklist.o
OBJS_040	= src/funcs_040.o src/iGameGUI_040.o src/iGameMain_040.o src/strfuncs_040.o src/fsfuncs_040.o src/blacklist_040.o src/WinBlacklist_040.o
OBJS_060	= src/funcs_060.o src/iGameGUI_060.o src/iGameMain_060.o src/strfuncs_060.o src/fsfuncs_060.o src/blacklist_060.o src/WinBlacklist_060.o
